name: online_groceries
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.7.0
  shared_preferences: ^2.1.0
  flutter_native_splash: 2.2.19
  intl_phone_field: 3.1.0
  font_awesome_flutter: 10.4.0
  pinput: 2.2.31
  dropdown_button2: ^2.0.0
  carousel_slider: 4.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/onbording/
    - assets/images/sign_in/
    - assets/images/select_location/
    - assets/images/home/
    - assets/images/explore/
    - assets/images/explore/beverages/
    - assets/images/explore/eggs/


  fonts: 
    - family: Gilroy
      fonts: 
        - asset: assets/fonts/Gilroy-Regular.ttf
  uses-material-design: true

flutter_native_splash: 
  color: '#53B175'
  image: assets/images/splash/splash_icon.png
  android: true
  ios: true

